<% if File.exists?("custom/config/database.yml") %>
  <%= ERB.new(File.read("custom/config/database.yml")).result %>
<% elsif File.exists?("../custom/config/database.yml") %>
  <%= ERB.new(File.read("../custom/config/database.yml")).result %>
<% else %>
test:
 adapter: sqlite3
 database: db/test.sqlite3
 pool: 5
 timeout: 5000

development:
 adapter: sqlite3
 database: db/development.sqlite3
 pool: 5
 timeout: 5000

staging:
 adapter: sqlite3
 database: db/staging.sqlite3
 pool: 5
 timeout: 5000

production:
 adapter: postgresql
 host: '<%= ENV['DB_HOST'] %>'
 port: <%= ENV['DB_PORT'] %>
 database: <%= ENV['DB_DATABASE'] %>
 encoding: unicode
 timeout: 5000
 pool: 5
 schema_search_path: '<%= ENV['DB_SCHEMA'] %>'
 username: '<%= ENV['DB_USERNAME'] %>'
 password: '<%= ENV['DB_PASSWORD'] %>'
<% end %>
